Document: libflint2
Title: Debian libflint2 Manual
Author: <insert document author here>
Abstract: This manual describes what libflint2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libflint2/libflint2.sgml.gz

Format: postscript
Files: /usr/share/doc/libflint2/libflint2.ps.gz

Format: text
Files: /usr/share/doc/libflint2/libflint2.text.gz

Format: HTML
Index: /usr/share/doc/libflint2/html/index.html
Files: /usr/share/doc/libflint2/html/*.html
